<?php
namespace app\models\Plans;

use yii\db\ActiveRecord;

class P0142_POGO2_  extends ActiveRecord
{
  public function attributeLabels() {
      return [
        'NOD' => 'НОД',
        'DATE' => 'РАСЧЕТНАЯ ДАТА',
        'VVS' => 'ВСЕГО ВАГ',
        'TVS' => 'ВСЕГО ТОН',
        'VUGOL' => 'УГОЛЬ ВАГ',
        'TUGOL' => 'УГОЛЬ ТОH',
        'VUGLP' => 'УГЛПР.ВАГ',
        'TUGLP' => 'УГЛПР.TOH',
        'VKOKS' => 'КОКС ВАГ',
        'TKOKS' => 'КОКС ТОH',
        'VNEFT' => 'НЕФТЬ ВАГ',
        'TNEFT' => 'НЕФТЬ ТОН',
        'VKNEF' => 'ГКНЕФ.ВАГ',
        'TKNEF' => 'ГКНЕФ.ТОН',
        'VTORF' => 'УЗКА ТОРФ',
        'TTORF' => 'УЗКА ТОРФ',
        'VFLUS' => 'ФЛЮСЫ.ВАГ',
        'TFLUS' => 'ФЛЮСЫ.TOH',
        'VRUDG' => 'РУД.Ж.ВАГ',
        'TRUDG' => 'РУД.Ж.TOH',
        'VRUDC' => 'РУД.Ц.ВАГ',
        'TRUDC' => 'РУД.Ц.ТОН',
        'VCHMT' => 'Ч.МЕТ.ВАГ',
        'TCHMT' => 'Ч.МЕТ.ТОН',
        'VMAOB' => 'МАШ.ОБ.ВАГ',
        'TMAOB' => 'МАШ.ОБ.ТОН',
        'VMETK' => 'МЕТКОН.ВАГ',
        'TMETK' => 'МЕТКОН.ТОН',
        'VMETZ' => 'МЕТИЗЫ.ВАГ',
        'TMETZ' => 'МЕТИЗЫ.ТОН',
        'VMETL' => 'МЕТЛОМ.ВАГ',
        'TMETL' => 'МЕТЛОМ.ТОН',
        'VCHMA' => 'СХМАШ.ВАГ',
        'TCHMA' => 'СХМАШ.ТОН',
        'VAVTO' => 'АВТОМ.ВАГ',
        'TAVTO' => 'АВТОМ.ТОН',
        'VCVMT' => 'ЦВ.МЕТ.ВАГ',
        'TCVMT' => 'ЦВ.МЕТ.ТОН',
        'VUDOB' => 'УДОБР.ВАГ',
        'TUDOB' => 'УДОБР.ТОН',
        'VHIMK' => 'XИМИКТ.ВАГ',
        'THIMK' => 'ХИМИКТ.ТОН',
        'VSTRG' => 'СТР.ГР.ВАГ',
        'TSTRG' => 'СТР.ГР.ТОН',
        'VPRMS' => 'ПРМСЫР.ВАГ',
        'TPRMS' => 'ПРМСЫР.ТОН',
        'VGRSH' => 'ГР.ШЛК.ВАГ',
        'TGRSH' => 'ГР.ШЛК.ТОН',
        'VOGNE' => 'ОГНЕУП.ВАГ',
        'TOGNE' => 'ОГНЕУП.ТОН',
        'VCEMN' => 'ЦЕМЕНТ.ВАГ',
        'TCEMN' => 'ЦЕМЕНТ.ТОН',
        'VLESG' => 'ЛЕС.ГР.ВАГ',
        'TLESG' => 'ЛЕС.ГР.ТОН',
        'VGLES' => 'ГЛВЛЕС.ВАГ',
        'TGLES' => 'ГЛВЛЕС.ТОН',
        'VSAHR' => 'САХАР ВАГ',
        'TSAHR' => 'САХАР ТОН',
        'VMISO' => 'МЯСО ВАГ',
        'TMISO' => 'МЯСО ТОН',
        'VRIBA' => 'РЫБА ВАГ',
        'TRIBA' => 'РЫБА ТОН',
        'VOVOC' => 'ОВОЩИ ВАГ',
        'TOVOC' => 'ОВОЩИ ТОН',
        'VKART' => 'КАРТОФ.ВАГ',
        'TKART' => 'КАРТОФ.ТОН',
        'VSOL' => 'СОЛЬ ВАГ',
        'TSOL' => 'СОЛЬ ТОН',
        'VPROD' => 'ПРОДТОВ.ВАГ',
        'TPROD' => 'ПРОДТОВ.ТОН',
        'VPROM' => 'ПРОМТОВ.ВАГ',
        'TPROM' => 'ПРОМТОВ.ТОН',
        'VHLOP' => 'ХЛОПОК ВАГ',
        'THLOP' => 'ХЛОПОК ТОН',
        'VSVEK' => 'СВЕКЛА ВАГ',
        'TSVEK' => 'СВЕКЛА ТОН',
        'VZERN' => 'ЗЕРНО ВАГ',
        'TZERN' => 'ЗЕРНО ТОН',
        'VMUKA' => 'МУКА ВАГ',
        'TMUKA' => 'МУКА ТОН',
        'VKOMB' => 'КОМБИК.ВАГ',
        'TKOMB' => 'КОМБИК.ТОН',
        'VGIVN' => 'ЖИВНС.ВАГ',
        'TGIVN' => 'ЖИВНC.ТОН',
        'VGMIH' => 'ЖМЫХИ.ВАГ',
        'TGMIH' => 'ЖМЫХИ.ТОН',
        'VBUMG' => 'БУМАГА.ВАГ',
        'TBUMG' => 'БУМАГА.ТОН',
        'VPRVV' => 'ПЕРЕВ.ВС.ВАГ',
        'TPRVV' => 'ПЕРЕВ.ВС.ТОН',
        'VPVUG' => 'ПРВЛ.УГЛ.ВАГ',
        'TPVUG' => 'ПРВЛ.УГЛ.ТОН',
        'VPVLS' => 'ПРВЛ.ЛЕС.ВАГ',
        'TPVLS' => 'ПРВЛ.ЛЕС.ТОН',
        'VPVIM' => 'ИМПОРТ ВАГ',
        'TPVIM' => 'ИМПОРТ ТОН',
        'VKONT' => 'ГР.КОНТ.ВАГ',
        'TKONT' => 'ГР.КОНТ.ТОН',
        'VOSGR' => 'ОСТАЛЬН.ВАГ',
        'TOSGR' => 'ОСТАЛЬН.ТОН',
        'VUDBR' => 'МИНУДОБ.ВАГ',
        'TUDBR' => 'МИНУДОБ.ТОН',
        'VMOSK' => 'МОСКВУ ВАГ',
        'TMOSK' => 'МОСКВУ ТОН',
        'VMOBL' => 'МОСОБЛ.ВАГ',
        'TMOBL' => 'МОСОБЛ.ТОН',
        'VIZUD' => 'ИЗВ.УДБ.ВАГ',
        'TIZUD' => 'ИЗВ.УДБ.ТОН',
        'VMLBP' => 'МИНЛЕСБУMПРОМ ВАГ',
        'TMLBP' => 'МИНЛЕСБУMПРОМ ТОН',
        'VSPRT' => 'СПИPT ПЕРЕВАЛКА ВАГ',
        'TSPRT' => 'СПИPT ПЕРЕВАЛКА ТОН',
        'VMPSP' => 'МИПОР.СПИРТА ВАГ',
        'TMPSP' => 'МИПОР.СПИРТА ТОН',
        'VSPVS' => 'СПИPT ВАГ',
        'TSPVS' => 'СПИPT ТОН',
      ];
  }
  /**
   * @return array the validation rules.
   */

  public function rules()
  {
    return [
      [['NOD','VVS','TVS','VUGOL','TUGOL','VUGLP','TUGLP','VKOKS','TKOKS','VNEFT','TNEFT','VKNEF','TKNEF',
      'VTORF','TTORF','VFLUS','TFLUS','VRUDG','TRUDG','VRUDC','TRUDC','VCHMT','TCHMT','VMAOB','TMAOB','VMETK',
      'TMETK','VMETZ','TMETZ','VMETL','TMETL','VCHMA','TCHMA','VAVTO','TAVTO','VCVMT','TCVMT','VUDOB','TUDOB',
      'VHIMK','THIMK','VSTRG','TSTRG','VPRMS','TPRMS','VGRSH','TGRSH','VOGNE','TOGNE','VCEMN','TCEMN','VLESG',
      'TLESG','VGLES','TGLES','VSAHR','TSAHR','VMISO','TMISO','VRIBA','TRIBA','VOVOC','TOVOC','VKART','TKART',
      'VSOL','TSOL','VPROD','TPROD','VPROM','TPROM','VHLOP','THLOP','VSVEK','TSVEK','VZERN','TZERN','VMUKA',
      'TMUKA','VKOMB','TKOMB','VGIVN','TGIVN','VGMIH','TGMIH','VBUMG','TBUMG','VPRVV','TPRVV','VPVUG','TPVUG',
      'VPVLS','TPVLS','VPVIM','TPVIM','VKONT','TKONT','VOSGR','TOSGR','VUDBR','TUDBR','VMOSK','TMOSK','VMOBL',
      'TMOBL','VIZUD','TIZUD','VMLBP','TMLBP','VSPRT','TSPRT'],
      'required', 'message' => 'Поле {attribute} обязательно для заполнения'],

      [['NOD','VVS','TVS','VUGOL','TUGOL','VUGLP','TUGLP','VKOKS','TKOKS','VNEFT','TNEFT','VKNEF','TKNEF',
      'VTORF','TTORF','VFLUS','TFLUS','VRUDG','TRUDG','VRUDC','TRUDC','VCHMT','TCHMT','VMAOB','TMAOB','VMETK',
      'TMETK','VMETZ','TMETZ','VMETL','TMETL','VCHMA','TCHMA','VAVTO','TAVTO','VCVMT','TCVMT','VUDOB','TUDOB',
      'VHIMK','THIMK','VSTRG','TSTRG','VPRMS','TPRMS','VGRSH','TGRSH','VOGNE','TOGNE','VCEMN','TCEMN','VLESG',
      'TLESG','VGLES','TGLES','VSAHR','TSAHR','VMISO','TMISO','VRIBA','TRIBA','VOVOC','TOVOC','VKART','TKART',
      'VSOL','TSOL','VPROD','TPROD','VPROM','TPROM','VHLOP','THLOP','VSVEK','TSVEK','VZERN','TZERN','VMUKA',
      'TMUKA','VKOMB','TKOMB','VGIVN','TGIVN','VGMIH','TGMIH','VBUMG','TBUMG','VPRVV','TPRVV','VPVUG','TPVUG',
      'VPVLS','TPVLS','VPVIM','TPVIM','VKONT','TKONT','VOSGR','TOSGR','VUDBR','TUDBR','VMOSK','TMOSK','VMOBL',
      'TMOBL','VIZUD','TIZUD','VMLBP','TMLBP','VSPRT','TSPRT','VMPSP','TMPSP','VSPVS','TSPVS'],
      'integer', 'message' => 'Поле {attribute} должно быть целочисленным'],

      ['NOD', 'string', 'max' => 2, 'min' => 1, 'tooLong' => 'Поле {attribute} должно иметь не более 2-х знаков'],
      [['VMPSP','TMPSP','VSPVS','TSPVS'], 'default', 'value' => 0],

      [['NOD','VVS','TVS','VUGOL','TUGOL','VUGLP','TUGLP','VKOKS','TKOKS','VNEFT','TNEFT','VKNEF','TKNEF',
      'VTORF','TTORF','VFLUS','TFLUS','VRUDG','TRUDG','VRUDC','TRUDC','VCHMT','TCHMT','VMAOB','TMAOB','VMETK',
      'TMETK','VMETZ','TMETZ','VMETL','TMETL','VCHMA','TCHMA','VAVTO','TAVTO','VCVMT','TCVMT','VUDOB','TUDOB',
      'VHIMK','THIMK','VSTRG','TSTRG','VPRMS','TPRMS','VGRSH','TGRSH','VOGNE','TOGNE','VCEMN','TCEMN','VLESG',
      'TLESG','VGLES','TGLES','VSAHR','TSAHR','VMISO','TMISO','VRIBA','TRIBA','VOVOC','TOVOC','VKART','TKART',
      'VSOL','TSOL','VPROD','TPROD','VPROM','TPROM','VHLOP','THLOP','VSVEK','TSVEK','VZERN','TZERN','VMUKA',
      'TMUKA','VKOMB','TKOMB','VGIVN','TGIVN','VGMIH','TGMIH','VBUMG','TBUMG','VPRVV','TPRVV','VPVUG','TPVUG',
      'VPVLS','TPVLS','VPVIM','TPVIM','VKONT','TKONT','VOSGR','TOSGR','VUDBR','TUDBR','VMOSK','TMOSK','VMOBL',
      'TMOBL','VIZUD','TIZUD','VMLBP','TMLBP','VSPRT','TSPRT','VMPSP','TMPSP','VSPVS','TSPVS'],
      'number', 'min'=> 0, 'tooSmall' => 'Поле {attribute} не должно быть отрицательным'],

    ];
  }
    /**
     * @return string название таблицы, сопоставленной с этим ActiveRecord-классом.
     */
    public static function tableName()
    {
        return '{{P0142_POGO2_}}';
    }
}
?>
